
TARGET = Ice

INCLUDE += $(OSPL_HOME)/include/dcps/C/SAC $(OSPL_HOME)/include $(OSPL_HOME)/include/sys
LIBPATH += $(OSPL_HOME)/lib
LIBS += ddskernel dcpssac

include $(CORTEX_HOME)/build/package.makefile
